[text]
appendEmptyLine=true
autoBracket=true
autoReplace=true
autoSave=true
autoSaveInterval=5
darkBgColorValue=15
darkColorScheme=true
dateFormat=
dictionaryPath=
executeCommand=
executeScripts=false
font="Noto Sans SignWriting,11,-1,5,50,0,0,0,0,0"
inertialScrolling=false
lightBgColorValue=255
lineNumbers=true
maxSHSize=2
noIndent=false
noSyntaxHighlighting=false
noWrap=false
openRecentFiles=0
pastePaths=true
recentFiles=/home/batan/Downloads/nom_2.1.1_linux_amd64/README.md, /media/batan/Q4OS/home/batan/check/caps.sh
recentFilesNumber=30
recentOpened=false
removeTrailingSpaces=false
saveLastFilesList=false
saveUnmodified=false
scrollJumpWorkaround=false
selectionHighlighting=true
showEndings=false
showWhiteSpace=false
skipNonText=true
spellCheckFromStart=false
textMargin=true
textTabSize=4
thickCursor=true
vLineDistance=-80

[window]
closeWithLastTab=false
disableMenubarAccel=true
fullscreen=false
hideSearchbar=true
hideSingleTab=false
iconless=false
max=true
menubarTitle=true
nativeDialog=true
noMenubar=false
noToolbar=true
openInWindows=false
position=@Point(37 23)
prefSize=@Size(421 530)
sharedSearchHistory=true
showCursorPos=true
showLangSelector=false
showStatusbar=false
sidePaneMode=true
size=@Size(1883 1057)
splitterPos=150
startSize=@Size(700 500)
sysIcon=true
sysIcons=true
tabPosition=0
tabWrapAround=false
